import { FormEvent, useEffect, useState } from "react";
import { Link, Navigate, Route, Routes, useParams } from "react-router-dom";
import { CareerDocumentsPage } from "./CareerPages";
import { CompleteCoursePage, FinalDefensePage, useCourseProgressMap } from "./CompleteCoursePages";
import { ALL_PROFESSIONAL_COURSES, PROFESSIONAL_PHASES } from "./curriculum";
import { CV_DECLARED_COMPETENCIES, EDUCONCRET_LEVELS, PROFESSIONAL_PATH } from "./professionalCatalog";
import { loadEvidence, saveMission } from "./professionalService";

function Gate({unlocked,children}:{unlocked:boolean;children:React.ReactNode}) {
  if(unlocked)return <>{children}</>;
  return <section className="card professional-lock"><span className="status-chip">🔒 Prérequis</span><h1>Le parcours professionnel est encore verrouillé</h1><p>Terminez le parcours « Réactualiser ses compétences… » ou obtenez sa validation explicite. Les 34 domaines resteront alors accessibles et chacun commencera par son propre positionnement.</p><Link className="primary" to="/course/jangat-ip-2026">Reprendre le parcours actuel</Link></section>;
}

function Hub() {
  const progress=useCourseProgressMap();const completed=Object.values(progress).filter(status=>status==="completed").length;
  return <><section className="professional-hero"><p className="eyebrow">Parcours professionnel complet · EduConcret</p><h1>{PROFESSIONAL_PATH.title}</h1><p>34 domaines, chacun avec positionnement adaptatif, cours complet, évaluation, mission et preuve. Le contenu reste consultable même lorsqu’une validation directe est recommandée.</p><div className="professional-actions"><Link className="primary" to="/professional/positioning">Voir mon bilan initial</Link><Link className="secondary-button" to="/professional/portfolio">Portfolio</Link><Link className="secondary-button" to="/professional/career">CV et carrière</Link></div></section><section className="card career-summary"><strong>{completed}/34</strong><span>domaines terminés sur preuve</span><div className="progress"><i style={{width:`${Math.round(100*completed/34)}%`}}/></div></section>
    {PROFESSIONAL_PHASES.map(phase=><section className="phase-block" key={phase.id}><div className="phase-heading"><div><p className="eyebrow">Progression recommandée</p><h2>{phase.title}</h2></div><p>{phase.description}</p></div><div className="professional-grid">{ALL_PROFESSIONAL_COURSES.filter(course=>course.phase===phase.id).map(course=><article className="card domain-card" key={course.id}><span className={`status-chip ${progress[course.id]==="completed"?"demonstrated":"declared"}`}>{progress[course.id]==="completed"?"Terminé":progress[course.id]||"À positionner"}</span><small>Domaine {course.order} · {course.durationHours} h</small><h3>{course.shortTitle}</h3><p>{course.objective}</p><Link to={`/professional/course/${course.id}`}>Positionnement et cours →</Link></article>)}</div></section>)}
    <section className="card"><h2>Niveaux EduConcret</h2><ol className="level-list">{EDUCONCRET_LEVELS.map((level,index)=><li key={level}><strong>Niveau {index+1}</strong><span>{level}</span></li>)}</ol></section></>;
}

function InitialPositioning() {
  return <><section className="course-intro"><p className="eyebrow">Bilan des acquis</p><h1>Point de départ déclaré, jamais validé automatiquement</h1><p>Le CV 2026 oriente le parcours. Chaque domaine possède ensuite huit évaluations distinctes : connaître, faire sans IA, faire avec IA, contrôler, expliquer, diriger, transmettre et prouver.</p></section><section className="card declared-block"><span className="status-chip declared">Déclaré · CV 2026</span><h2>Acquis recensés</h2><div className="chip-grid">{CV_DECLARED_COMPETENCIES.map(item=><span key={item.id}>{item.title}</span>)}</div></section><section className="card"><h2>Commencer le positionnement domaine par domaine</h2><div className="lesson-list">{ALL_PROFESSIONAL_COURSES.map(course=><article key={course.id}><strong>{course.order}. {course.title}</strong><Link to={`/professional/course/${course.id}`}>Évaluer ce domaine →</Link></article>)}</div></section></>;
}

function Mission() {
  const {missionId}=useParams();const course=ALL_PROFESSIONAL_COURSES.find(item=>item.mission.id===missionId);const [explanation,setExplanation]=useState("");const [delivery,setDelivery]=useState("");const [criteria,setCriteria]=useState<Record<string,string>>({});const [uses,setUses]=useState<string[]>([]);const [notice,setNotice]=useState("");
  if(!course)return <Navigate to="/professional"/>;
  const mission=course.mission;const valid=explanation.trim().length>=300&&delivery.trim().length>=500&&mission.criteria.every(criterion=>criteria[criterion]);
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!valid)return;const result=await saveMission({missionId:mission.id,missionTitle:mission.title,courseKey:course.id,operationalDelivery:delivery,personalExplanation:explanation,criteria,aiUsage:uses});setNotice(result.demonstrated?`Mission version ${result.version} démontrée après contrôle.`:`Version ${result.version} soumise. Elle reste en attente d’une revue indépendante avant toute validation.`)};
  return <><Link className="back" to={`/professional/course/${course.id}`}>← Cours</Link><section className="course-intro"><p className="eyebrow">Mission professionnelle · Domaine {course.order}</p><h1>{mission.title}</h1><p>{mission.context}</p></section><form className="card professional-form" onSubmit={submit}><div className="critical"><strong>Critère critique</strong><p>{mission.criticalCriterion}</p></div><label>1. Explication personnelle avant toute aide IA<textarea value={explanation} onChange={event=>setExplanation(event.target.value)} placeholder="Votre raisonnement, vos hypothèses, vos arbitrages et vos limites."/></label><label>2. Livrable professionnel<textarea value={delivery} onChange={event=>setDelivery(event.target.value)} placeholder={mission.deliverable}/></label><fieldset><legend>3. Grille d’évaluation</legend>{mission.criteria.map(criterion=><label className="criterion" key={criterion}><span>{criterion}</span><select value={criteria[criterion]||""} onChange={event=>setCriteria({...criteria,[criterion]:event.target.value})}><option value="">À évaluer</option><option>Respecté</option><option>Partiel</option><option>Non respecté</option></select></label>)}</fieldset><fieldset><legend>4. Usage de l’IA</legend>{["Aucune IA","Recherche","Structuration","Production","Critique","Reformulation","Calcul ou analyse"].map(use=><label className="check" key={use}><input type="checkbox" checked={uses.includes(use)} onChange={event=>setUses(event.target.checked?[...uses,use]:uses.filter(item=>item!==use))}/>{use}</label>)}</fieldset><p className="form-hint">La mission ne peut être soumise qu’après réussite de l’évaluation du domaine et ne devient démontrée qu’après une revue indépendante. Aucune donnée confidentielle ou personnelle ne doit être transmise à une IA. Une auto-évaluation « Partiel » ou « Non respecté » crée une preuve en cours, jamais démontrée.</p><button className="primary" disabled={!valid}>Enregistrer cette version</button>{notice&&<div className={notice.includes("démontrée")?"feedback ok":"feedback error"} role="status"><p>{notice}</p></div>}</form></>;
}

function Portfolio() {
  const [evidence,setEvidence]=useState<Array<{id:string;mission_key:string;title:string;status:string;created_at:string}>>([]);const [error,setError]=useState("");
  useEffect(()=>{loadEvidence().then(rows=>setEvidence(rows as typeof evidence)).catch(caught=>setError(caught instanceof Error?caught.message:String(caught)))},[]);
  return <><section className="course-intro"><p className="eyebrow">Portfolio professionnel</p><h1>Preuves, versions et statuts</h1><p>Une production en cours reste distincte d’une preuve démontrée ou confirmée.</p></section>{error&&<div className="feedback error">{error}</div>}<div className="professional-grid">{evidence.length?evidence.map(item=><article className="card" key={item.id}><span className={`status-chip ${item.status}`}>{item.status}</span><h3>{item.title}</h3><p>{item.mission_key}</p><small>{new Date(item.created_at).toLocaleDateString("fr-FR")}</small></article>):<article className="card"><h2>Aucune preuve enregistrée</h2><p>Commencez une mission autonome. Les acquis du CV restent déclarés tant qu’aucune production n’est démontrée.</p></article>}</div></>;
}

function FeatureRoutes({unlocked}:{unlocked:boolean}) {
  return <Gate unlocked={unlocked}><Routes><Route index element={<Hub/>}/><Route path="positioning" element={<InitialPositioning/>}/><Route path="course/:courseId" element={<CompleteCoursePage/>}/><Route path="domain/:courseId" element={<CompleteCoursePage/>}/><Route path="mission/:missionId" element={<Mission/>}/><Route path="portfolio" element={<Portfolio/>}/><Route path="defense" element={<FinalDefensePage/>}/><Route path="career" element={<CareerDocumentsPage/>}/><Route path="*" element={<Navigate to="/professional"/>}/></Routes></Gate>;
}

export default FeatureRoutes;
