import { FormEvent, useEffect, useMemo, useState } from "react";
import { Link, Navigate, useParams } from "react-router-dom";
import {
  AI_LEVELS, buildCvSuggestions, canValidateMission, COMPETENCY_STATUSES,
  CV_DECLARED_COMPETENCIES, EDUCONCRET_LEVELS, POSITIONING_DIMENSIONS,
  PROFESSIONAL_DOMAINS, PROFESSIONAL_MISSIONS, PROFESSIONAL_PATH, SOURCE_REGISTRY,
} from "./professionalCatalog";
import { loadEvidence, saveMission, savePositioning } from "./professionalService";

type WrapperProps = { unlocked: boolean; children: React.ReactNode };
export function ProfessionalGate({ unlocked, children }: WrapperProps) {
  if (unlocked) return <>{children}</>;
  return <section className="card professional-lock"><span className="status-chip">🔒 Prérequis</span><h1>Le parcours professionnel est encore verrouillé</h1><p>Terminez le parcours « Réactualiser ses compétences… » ou obtenez sa validation explicite. Vos acquis du CV restent déclarés, jamais considérés comme démontrés automatiquement.</p><Link className="primary" to="/course/jangat-ip-2026">Reprendre le parcours actuel</Link></section>;
}

export function ProfessionalHub({ unlocked }: { unlocked: boolean }) {
  return <ProfessionalGate unlocked={unlocked}><section className="professional-hero"><p className="eyebrow">Nouveau parcours · EduConcret</p><h1>{PROFESSIONAL_PATH.title}</h1><p>{PROFESSIONAL_PATH.subtitle}. Un parcours de direction fondé sur des missions, des preuves et une utilisation contrôlée de l’IA.</p><div className="professional-actions"><Link className="primary" to="/professional/positioning">Faire mon bilan initial</Link><Link className="secondary-button" to="/portfolio">Voir mon portfolio</Link></div></section>
    <section className="card declared-block"><span className="status-chip declared">Déclaré · CV 2026</span><h2>Vos acquis importés comme point de départ</h2><p>Ces éléments orientent le positionnement. Ils ne sont ni évalués ni validés.</p><div className="chip-grid">{CV_DECLARED_COMPETENCIES.map(c=><span key={c.id}>{c.title}</span>)}</div></section>
    <section><h2>Blocs pilotes</h2><div className="professional-grid">{PROFESSIONAL_DOMAINS.map(domain=><article className="card domain-card" key={domain.id}><span className={`status-chip ${domain.status}`}>{domain.status==="operational"?"Opérationnel":"Préparatoire"}</span><h3>{domain.title}</h3><p>{domain.target}</p><Link to={`/professional/domain/${domain.id}`}>Ouvrir le bloc →</Link></article>)}</div></section>
    <section className="card"><h2>Progression EduConcret</h2><ol className="level-list">{EDUCONCRET_LEVELS.map((level,index)=><li key={level}><strong>Niveau {index+1}</strong><span>{level}</span></li>)}</ol></section></ProfessionalGate>;
}

export function PositioningPage({ unlocked }: { unlocked: boolean }) {
  const [competencyId,setCompetencyId]=useState<string>(CV_DECLARED_COMPETENCIES[0].id);
  const [dimensions,setDimensions]=useState<Record<string,number>>(()=>Object.fromEntries(POSITIONING_DIMENSIONS.map(d=>[d,1])));
  const [status,setStatus]=useState("déclaré");const [aiLevel,setAiLevel]=useState("A");const [notice,setNotice]=useState("");
  const submit=async(e:FormEvent)=>{e.preventDefault();await savePositioning({competencyId,dimensions,status,aiLevel});setNotice("Positionnement enregistré dans votre espace sécurisé.")};
  return <ProfessionalGate unlocked={unlocked}><section className="course-intro"><p className="eyebrow">Bilan initial</p><h1>Positionnement multidimensionnel</h1><p>Évaluez chaque dimension séparément. Une déclaration n’est pas une preuve.</p></section><form className="card professional-form" onSubmit={submit}><label>Compétence issue du CV<select value={competencyId} onChange={e=>setCompetencyId(e.target.value)}>{CV_DECLARED_COMPETENCIES.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><div className="dimension-grid">{POSITIONING_DIMENSIONS.map(d=><label key={d}><span>{d}</span><input type="range" min="1" max="7" value={dimensions[d]} onChange={e=>setDimensions({...dimensions,[d]:Number(e.target.value)})}/><strong>{dimensions[d]}/7</strong></label>)}</div><label>Statut<select value={status} onChange={e=>setStatus(e.target.value)}>{COMPETENCY_STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label>Autonomie IA<select value={aiLevel} onChange={e=>setAiLevel(e.target.value)}>{AI_LEVELS.map(l=><option value={l.id} key={l.id}>{l.id} — {l.label}</option>)}</select></label><button className="primary">Enregistrer ce positionnement</button>{notice&&<p role="status">{notice}</p>}</form></ProfessionalGate>;
}

export function DomainPage({ unlocked }: { unlocked: boolean }) {
  const {domainId}=useParams();const domain=PROFESSIONAL_DOMAINS.find(d=>d.id===domainId);if(!domain)return <Navigate to="/professional"/>;
  const sources=SOURCE_REGISTRY.filter(source=>domain.sourceIds.includes(source.id));
  return <ProfessionalGate unlocked={unlocked}><Link className="back" to="/professional">← Parcours professionnel</Link><section className="course-intro"><p className="eyebrow">{domain.status==="operational"?"Bloc opérationnel":"Bloc préparatoire"}</p><h1>{domain.title}</h1><p>{domain.target}</p></section><div className="professional-grid two"><article className="card"><h2>Notion</h2><p>{domain.notion}</p></article><article className="card"><h2>Méthode</h2><p>{domain.method}</p></article><article className="card"><h2>Exemple EduConcret</h2><p>{domain.example}</p></article><article className="card"><h2>Sources vérifiables</h2>{sources.map(source=><a className="source-link" href={source.url} target="_blank" rel="noreferrer" key={source.id}>{source.authority} · {source.title}<small>Vérifiée le {source.checkedAt}</small></a>)}</article></div><Link className="primary mission-cta" to={`/professional/mission/${domain.missionId}`}>Réaliser la mission</Link></ProfessionalGate>;
}

export function MissionPage({ unlocked }: { unlocked: boolean }) {
  const {missionId}=useParams();const mission=PROFESSIONAL_MISSIONS.find(m=>m.id===missionId);const [explanation,setExplanation]=useState("");const [delivery,setDelivery]=useState("");const [criteria,setCriteria]=useState<Record<string,string>>({});const [uses,setUses]=useState<string[]>([]);const [notice,setNotice]=useState("");
  if(!mission)return <Navigate to="/professional"/>;
  const valid=canValidateMission(explanation,delivery)&&mission.criteria.every(c=>criteria[c]);
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!valid)return;const result=await saveMission({missionId:mission.id,missionTitle:mission.title,courseKey:mission.domainId,operationalDelivery:delivery,personalExplanation:explanation,criteria,aiUsage:uses});setNotice(result.demonstrated?"Mission enregistrée. Une preuve démontrée a été ajoutée au portfolio.":"Mission enregistrée pour correction. La preuve reste en cours.")};
  return <ProfessionalGate unlocked={unlocked}><Link className="back" to={`/professional/domain/${mission.domainId}`}>← Bloc</Link><section className="course-intro"><p className="eyebrow">Mission professionnelle</p><h1>{mission.title}</h1><p>{mission.context}</p></section><form className="card professional-form" onSubmit={submit}><div className="critical"><strong>Critère critique</strong><p>{mission.criticalCriterion}</p></div><label>1. Votre analyse personnelle avant toute aide IA<textarea value={explanation} onChange={e=>setExplanation(e.target.value)} placeholder="Expliquez votre raisonnement, vos hypothèses et vos décisions (80 caractères minimum)."/></label><label>2. Livrable opérationnel<textarea value={delivery} onChange={e=>setDelivery(e.target.value)} placeholder={mission.operationalDeliverable}/></label><fieldset><legend>3. Auto-évaluation critériée</legend>{mission.criteria.map(c=><label className="criterion" key={c}><span>{c}</span><select value={criteria[c]||""} onChange={e=>setCriteria({...criteria,[c]:e.target.value})}><option value="">À évaluer</option><option>Respecté</option><option>Partiel</option><option>Non respecté</option></select></label>)}</fieldset><fieldset><legend>4. Journal d’usage de l’IA</legend>{["Recherche d’idées","Structuration","Critique","Reformulation","Aucune IA"].map(use=><label className="check" key={use}><input type="checkbox" checked={uses.includes(use)} onChange={e=>setUses(e.target.checked?[...uses,use]:uses.filter(item=>item!==use))}/>{use}</label>)}</fieldset><p className="form-hint">Le mot de passe, les données personnelles et les documents confidentiels ne doivent jamais être transmis à une IA.</p><button className="primary" disabled={!valid}>Soumettre la mission et créer la preuve</button>{notice&&<p role="status">{notice}</p>}</form></ProfessionalGate>;
}

export function PortfolioPage({ unlocked }: { unlocked: boolean }) {
  const [evidence,setEvidence]=useState<Array<{id:string;mission_key:string;title:string;status:string;created_at:string}>>([]);const [error,setError]=useState("");
  useEffect(()=>{if(unlocked)loadEvidence().then(rows=>setEvidence(rows as typeof evidence)).catch(err=>setError(err instanceof Error?err.message:String(err)))},[unlocked]);
  return <ProfessionalGate unlocked={unlocked}><section className="course-intro"><p className="eyebrow">Portfolio probatoire</p><h1>Vos preuves professionnelles</h1><p>Le portfolio sépare ce qui est déclaré, en cours, démontré et confirmé.</p></section>{error&&<div className="feedback error">{error}</div>}<div className="professional-grid">{evidence.length?evidence.map(item=><article className="card" key={item.id}><span className="status-chip demonstrated">{item.status}</span><h3>{item.title}</h3><p>Mission : {item.mission_key}</p><small>{new Date(item.created_at).toLocaleDateString("fr-FR")}</small></article>):<article className="card"><h2>Aucune preuve démontrée</h2><p>Les compétences du CV sont déclarées. Réalisez une mission pour produire une première preuve.</p><Link to="/professional">Choisir une mission →</Link></article>}</div></ProfessionalGate>;
}

export function CvEvidencePage({ unlocked }: { unlocked: boolean }) {
  const [evidence,setEvidence]=useState<Array<{title:string;status:string}>>([]);useEffect(()=>{if(unlocked)loadEvidence().then(rows=>setEvidence(rows as typeof evidence)).catch(()=>setEvidence([]))},[unlocked]);const suggestions=useMemo(()=>buildCvSuggestions(evidence),[evidence]);
  return <ProfessionalGate unlocked={unlocked}><section className="course-intro"><p className="eyebrow">CV fondé sur les preuves</p><h1>Formulations provisoires</h1><p>JÀNGAT ne transforme jamais une déclaration en compétence validée. Ces formulations restent à relire et à contextualiser.</p></section><section className="card"><h2>Compétences déclarées depuis le CV</h2><div className="chip-grid">{CV_DECLARED_COMPETENCIES.map(c=><span key={c.id}>{c.title}</span>)}</div></section><section className="card cv-suggestions"><h2>Suggestions soutenues par une preuve</h2>{suggestions.length?<ul>{suggestions.map(s=><li key={s}>{s}</li>)}</ul>:<p>Aucune suggestion n’est encore autorisée. Il faut d’abord une mission soumise et une preuve démontrée.</p>}</section></ProfessionalGate>;
}
