import type { SourceReference } from "./curriculumTypes";

export const SUPPLEMENTAL_PROFESSIONAL_SOURCES: SourceReference[] = [
  {
    id: "1edtech-lti",
    title: "Learning Tools Interoperability (LTI)",
    authority: "1EdTech Consortium",
    url: "https://www.1edtech.org/standards/lti",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "adlnet-xapi",
    title: "Experience API (xAPI) specification",
    authority: "Advanced Distributed Learning Initiative (ADL)",
    url: "https://github.com/adlnet/xAPI-Spec",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "anact-competences-travail",
    title: "Compétences et parcours professionnel",
    authority: "Agence nationale pour l’amélioration des conditions de travail (Anact)",
    url: "https://www.anact.fr/taxonomy/term/11852",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "anssi-cyber-guide",
    title: "Recommandations de sécurité pour un système d’IA générative",
    authority: "Agence nationale de la sécurité des systèmes d’information (ANSSI)",
    url: "https://messervices.cyber.gouv.fr/guides/recommandations-de-securite-pour-un-systeme-dia-generative",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "british-council-business-english",
    title: "Business English learning resources",
    authority: "British Council",
    url: "https://learnenglish.britishcouncil.org/free-resources/business",
    kind: "executive",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "cefr-companion-2020",
    title: "Common European Framework of Reference for Languages — Companion Volume 2020",
    authority: "Council of Europe",
    url: "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-companion-volume-and-its-language-versions",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "apec-cadres",
    title: "Fiches métiers cadres",
    authority: "Apec",
    url: "https://www.apec.fr/tous-nos-metiers.html",
    kind: "executive",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 3,
  },
  {
    id: "atd-capability-model",
    title: "Talent Development Capability Model",
    authority: "Association for Talent Development (ATD)",
    url: "https://www.td.org/capability-model",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "bpifrance-plan-tresorerie",
    title: "Le plan de trésorerie dans un projet de création d’entreprise",
    authority: "Bpifrance Création",
    url: "https://bpifrance-creation.fr/encyclopedie/previsions-financieres-business-plan/previsions-financieres/plan-tresorerie-projet",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "cipd-ld-factsheet",
    title: "Learning and development — resources and factsheets",
    authority: "Chartered Institute of Personnel and Development (CIPD)",
    url: "https://www.cipd.org/en/topics/learning-development/",
    kind: "executive",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "cipd-ld-strategy",
    title: "Learning and development strategy and policy",
    authority: "Chartered Institute of Personnel and Development (CIPD)",
    url: "https://www.cipd.org/uk/knowledge/factsheets/strategy-development-factsheet/",
    kind: "executive",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "cipd-leadership",
    title: "Leadership in the workplace",
    authority: "Chartered Institute of Personnel and Development (CIPD)",
    url: "https://www.cipd.org/uk/knowledge/factsheets/leadership-factsheet/",
    kind: "executive",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "cipd-learning-needs-analysis",
    title: "Learning needs analysis",
    authority: "Chartered Institute of Personnel and Development (CIPD)",
    url: "https://www.cipd.org/uk/knowledge/factsheets/learning-needs-factsheet/",
    kind: "executive",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "cipd-learning-evaluation",
    title: "Learning evaluation, impact and transfer",
    authority: "Chartered Institute of Personnel and Development (CIPD)",
    url: "https://www.cipd.org/en/knowledge/factsheets/evaluating-learning-factsheet/",
    kind: "executive",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "cnil-formation-donnees",
    title: "Comprendre le RGPD",
    authority: "Commission nationale de l’informatique et des libertés (CNIL)",
    url: "https://www.cnil.fr/fr/comprendre-le-rgpd",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 3,
  },
  {
    id: "code-travail-convention-formation",
    title: "Convention de formation entre l’acheteur et l’organisme — article L6353-1",
    authority: "Légifrance",
    url: "https://www.legifrance.gouv.fr/codes/id/LEGISCTA000006189926",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 3,
  },
  {
    id: "code-travail-organisme-formation",
    title: "Code du travail — organismes de formation",
    authority: "Légifrance",
    url: "https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006072050/LEGISCTA000018498940/",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 3,
  },
  {
    id: "code-travail-qualiopi",
    title: "Code du travail — qualité des actions de formation professionnelle",
    authority: "Légifrance",
    url: "https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006072050/LEGISCTA000028689388/",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 3,
  },
  {
    id: "deans-for-impact-science-learning",
    title: "The Science of Learning",
    authority: "Deans for Impact",
    url: "https://www.deansforimpact.org/",
    kind: "research",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "digcomp-2-2",
    title: "DigComp 2.2 — The Digital Competence Framework for Citizens",
    authority: "Joint Research Centre — European Commission",
    url: "https://publications.jrc.ec.europa.eu/repository/handle/JRC128415",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "digcompedu",
    title: "Digital Competence Framework for Educators (DigCompEdu)",
    authority: "Joint Research Centre — European Commission",
    url: "https://joint-research-centre.ec.europa.eu/digcompedu_en",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "europass-cv",
    title: "Create your Europass CV",
    authority: "Europass — European Union",
    url: "https://europass.europa.eu/en/create-europass-cv",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "economie-gouv-acces-pme-commande-publique",
    title: "L’accès des PME à la commande publique",
    authority: "Direction des Achats de l’État — Ministère de l’Économie",
    url: "https://www.economie.gouv.fr/dae/la-politique-des-achats-de-letat/lacces-des-pme-la-commande-publique",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "economie-gouv-guide-marches-publics",
    title: "Conseils et guides relatifs aux marchés publics",
    authority: "Direction des Affaires juridiques — Ministère de l’Économie",
    url: "https://www.economie.gouv.fr/daj/conseils-aux-acheteurs-et-aux-autorites-concedantes",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "economie-gouv-prix-marches-publics",
    title: "Guide pratique — le prix dans les marchés publics",
    authority: "Direction des Affaires juridiques — Ministère de l’Économie",
    url: "https://www.economie.gouv.fr/daj/publication-de-la-version-2023-du-guide-pratique-de-loecp-le-prix-dans-les-marches-publics",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "fc-search",
    title: "Moteur de recherche RNCP et Répertoire spécifique",
    authority: "France compétences",
    url: "https://www.francecompetences.fr/recherche-resultats/",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 1,
  },
  {
    id: "fc-vademecum-2026",
    title: "Vademecum relatif à la certification professionnelle — janvier 2026",
    authority: "France compétences",
    url: "https://www.francecompetences.fr/app/uploads/2026/01/Vademecum-VF_2026.pdf",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 3,
  },
  {
    id: "france-travail-metierscope",
    title: "MétierScope — métiers, compétences et marché du travail",
    authority: "France Travail",
    url: "https://candidat.francetravail.fr/metierscope/marche-du-travail/accueil",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 1,
  },
  {
    id: "francecompetences-npec",
    title: "Niveaux de prise en charge des contrats d’apprentissage",
    authority: "France compétences",
    url: "https://www.francecompetences.fr/reguler-le-marche/niveaux-de-prise-en-charge-des-contrats-dapprentissage/",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 1,
  },
  {
    id: "harvard-negotiation",
    title: "Negotiation Preparation Strategies",
    authority: "Program on Negotiation at Harvard Law School",
    url: "https://www.pon.harvard.edu/daily/business-negotiations/negotiation-preparation-strategies/",
    kind: "executive",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "ies-organizing-instruction",
    title: "Organizing Instruction and Study to Improve Student Learning",
    authority: "Institute of Education Sciences — What Works Clearinghouse",
    url: "https://ies.ed.gov/ncee/wwc/PracticeGuide/1",
    kind: "research",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 24,
  },
  {
    id: "iso-21001",
    title: "ISO 21001:2025 — Management systems for educational organizations",
    authority: "International Organization for Standardization (ISO)",
    url: "https://www.iso.org/standard/21001",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "iso-30422",
    title: "ISO 30422:2022 — Human resource management: learning and development",
    authority: "International Organization for Standardization (ISO)",
    url: "https://www.iso.org/standard/76365.html",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "iso-30414",
    title: "ISO 30414:2025 — Human capital reporting and disclosure",
    authority: "International Organization for Standardization (ISO)",
    url: "https://www.iso.org/standard/30414",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "kirkpatrick-model",
    title: "The Kirkpatrick Model",
    authority: "Kirkpatrick Partners",
    url: "https://www.kirkpatrickpartners.com/the-kirkpatrick-model/",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "legifrance-certification-professionnelle",
    title: "Code du travail — certification professionnelle",
    authority: "Légifrance",
    url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000038951917",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 3,
  },
  {
    id: "legifrance-code-travail-fp",
    title: "Code du travail — formation professionnelle",
    authority: "Légifrance",
    url: "https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006072050/LEGISCTA000006145422/",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 3,
  },
  {
    id: "mesdemarches-bpf",
    title: "Mon activité formation — télédéclaration du bilan pédagogique et financier",
    authority: "Ministère du Travail — DGEFP",
    url: "https://www.monactiviteformation.emploi.gouv.fr/mon-activite-formation/",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 1,
  },
  {
    id: "moodle-docs",
    title: "Moodle documentation",
    authority: "Moodle",
    url: "https://docs.moodle.org/",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "nist-ai-rmf",
    title: "Artificial Intelligence Risk Management Framework",
    authority: "National Institute of Standards and Technology (NIST)",
    url: "https://www.nist.gov/itl/ai-risk-management-framework",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 3,
  },
  {
    id: "oecd-ai",
    title: "OECD AI Principles",
    authority: "Organisation for Economic Co-operation and Development (OECD)",
    url: "https://www.oecd.org/en/topics/ai-principles.html",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "oecd-skills-strategy",
    title: "OECD Skills Strategy",
    authority: "Organisation for Economic Co-operation and Development (OECD)",
    url: "https://www.oecd.org/en/topics/sub-issues/skills-strategies.html",
    kind: "research",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "pmi-governance",
    title: "Governance of Portfolios, Programs, and Projects — PMI practice guide",
    authority: "Project Management Institute (PMI)",
    url: "https://www.pmi.org/standards",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "pmi-pmbok7",
    title: "PMBOK Guide — official publication page",
    authority: "Project Management Institute (PMI)",
    url: "https://www.pmi.org/standards/pmbok",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "pmi-portfolio-management",
    title: "The Standard for Portfolio Management",
    authority: "Project Management Institute (PMI)",
    url: "https://www.pmi.org/standards",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "pmi-program-management",
    title: "The Standard for Program Management",
    authority: "Project Management Institute (PMI)",
    url: "https://www.pmi.org/standards",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "pmi-standard",
    title: "Project management standards",
    authority: "Project Management Institute (PMI)",
    url: "https://www.pmi.org/standards/about",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "rgaa-4-1-2",
    title: "Référentiel général d’amélioration de l’accessibilité — version 4.1.2",
    authority: "Direction interministérielle du numérique (DINUM)",
    url: "https://accessibilite.numerique.gouv.fr/",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 3,
  },
  {
    id: "service-public-bpf",
    title: "Déclaration et dépôt du bilan pédagogique et financier",
    authority: "Entreprendre Service Public",
    url: "https://entreprendre.service-public.gouv.fr/vosdroits/R53727",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 1,
  },
  {
    id: "service-public-plan-developpement-competences",
    title: "Plan de développement des compétences",
    authority: "Service Public",
    url: "https://www.service-public.fr/particuliers/vosdroits/F11267",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "service-public-obligations-comptables",
    title: "Règles comptables des entreprises",
    authority: "Entreprendre Service Public",
    url: "https://entreprendre.service-public.fr/vosdroits/N31383",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "service-public-organisme-formation",
    title: "Déclaration d’activité des formateurs et organismes de formation",
    authority: "Entreprendre Service Public",
    url: "https://entreprendre.service-public.gouv.fr/vosdroits/F19087",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 3,
  },
  {
    id: "travail-emploi-bpf",
    title: "Bilan pédagogique et financier — formulaire officiel",
    authority: "Ministère du Travail",
    url: "https://travail-emploi.gouv.fr/sites/travail-emploi/files/files-spip/pdf/bilan_pedagogique_et_financier.pdf",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 1,
  },
  {
    id: "travail-emploi-formation-professionnelle",
    title: "Formation professionnelle",
    authority: "Ministère du Travail",
    url: "https://travail-emploi.gouv.fr/formation-professionnelle",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 3,
  },
  {
    id: "travail-emploi-gepp",
    title: "Gestion des emplois et des parcours professionnels (GEPP)",
    authority: "Ministère du Travail — DEETS de La Réunion",
    url: "https://reunion.deets.gouv.fr/Gestion-des-emplois-et-des-parcours-professionnels-GEPP",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 6,
  },
  {
    id: "travail-emploi-opco",
    title: "Les opérateurs de compétences (OPCO)",
    authority: "Ministère du Travail",
    url: "https://travail-emploi.gouv.fr/les-operateurs-de-competences-opco",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 1,
  },
  {
    id: "travail-emploi-qualiopi",
    title: "Qualiopi — marque de certification qualité des prestataires de formation",
    authority: "Ministère du Travail",
    url: "https://travail-emploi.gouv.fr/qualiopi-marque-de-certification-qualite-des-prestataires-de-formation",
    kind: "official",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 3,
  },
  {
    id: "unesco-futures-education",
    title: "Reimagining our futures together — report resources",
    authority: "UNESCO",
    url: "https://www.unesco.org/en/futures-education/report-resources",
    kind: "research",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
  {
    id: "w3c-wcag22",
    title: "Web Content Accessibility Guidelines (WCAG) 2.2",
    authority: "World Wide Web Consortium (W3C)",
    url: "https://www.w3.org/TR/WCAG22/",
    kind: "standard",
    checkedAt: "2026-07-16",
    reviewFrequencyMonths: 12,
  },
];
